# EcoWaystone Configuration File
# Locale for language files (lang-{locale}.yml)
locale: "en_US"

# Admin Waystone System
admin-waystones:
  # Enable admin waystone system
  enabled: true
  # ItemsAdder item ID for waystone blocks
  waystone-item: "ecowaystone:waystone"
  # Default icon for waystones in GUI
  default-icon: "ecowaystone:waystone"
  # Enable discovery rewards
  enable-rewards: true
  # Sound effect when discovering a waystone
  discovery-sound: "ENTITY_PLAYER_LEVELUP"
  # Broadcast discovery to all players
  broadcast-discovery: false
  # Show distance in GUI
  show-distance: true
  # Discovery cost with Vault
  discovery-cost: 1000.0
  # GUI settings
  gui:
    title: "&bWaystones"
    rows: 6
    fill-empty-slots: true


# Zone Discovery System
zones:
  discovery:
    title: "Région découverte !"
    subtitle: "Vous avez découvert %zone%"
    sound:
      # Son à jouer lors de la découverte d'une zone
      # Formats supportés:
      # - Sons Minecraft vanilla: ENTITY_PLAYER_LEVELUP, UI_TOAST_CHALLENGE_COMPLETE
      # - Sons custom du resource pack: votre_pack:discovery_sound
      name: "ENTITY_PLAYER_LEVELUP"
      volume: 1.0
      pitch: 1.2

